{% set name = "pytest-shutil" %}
{% set version = "1.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8165261de76e7508505c341d94c02b113dc963f274543abca74dbfabd021261

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - contextlib2
    - execnet
    - mock
    - path.py
    - pip
    - pytest
    - python
    - setuptools
    - setuptools-git
    - six
    - termcolor
  run:
    - contextlib2
    - execnet
    - mock
    - path.py
    - pytest
    - python
    - six
    - termcolor

test:
  imports:
    - pytest_shutil
  commands:
    - pip check
  requires:
    - pytest
    - pip

about:
  home: https://github.com/manahl/pytest-plugins
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: A goodie-bag of unix shell and environment tools for py.test
  doc_url: https://github.com/manahl/pytest-plugins/tree/master/pytest-shutil#readme
  dev_url: https://github.com/manahl/pytest-plugins

extra:
  recipe-maintainers:
    - jcfr
